language: cpp
dist: bionic
cache: pip

matrix:
  include:
    - os: linux
      sudo: required
      compiler:
        - gcc
      env: COVERAGE=1
      before_script:
        - sudo apt-get install lcov
    - os: linux
      compiler:
        - clang
    - os: osx
      compiler:
        - clang
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir Build-Debug && cd Build-Debug
  - conan install ..
script:
  - cmake  -DCMAKE_BUILD_TYPE=Debug ..
  - |
    if [[ "${COVERAGE}" == "1" ]]; then
         cmake  -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On ..
         make -j2 && make test gcov lcov
    else
         cmake  -DCMAKE_BUILD_TYPE=Debug ..
         make -j2 && ctest -j2
    fi
after_success:
  - |
    if [[ "${COVERAGE}" == "1" ]]; then
        bash <(curl -s https://codecov.io/bash) -X gcov
    fi
