language: cpp
dist: bionic
cache: pip
matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - mkdir build && cd build
  - conan install ..
script:
  - cmake ..
  - make -j2
  - ctest -j2
