language: cpp
dist: bionic
cache: pip

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-bionic-6.0

matrix:
  include:
    - os: linux
      compiler:
        - gcc
    - os: linux
      compiler:
        - clang
    - os: osx
      compiler:
        - clang
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - mkdir build && cd build
  - conan install ..
script:
  - cmake ..
  - make -j2
  - ctest -j2
