language: cpp
dist: bionic
cache: pip

matrix:
  include:
    - os: linux
      compiler:
        - gcc
      env: COVERAGE=1
    - os: linux
      compiler:
        - clang
    - os: osx
      compiler:
        - clang
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -BBuild-Debug -DCMAKE_BUILD_TYPE=Debug -Wall
  - cmake -H. -BBuild-Release -DCMAKE_BUILD_TYPE=Release -Wall
  - cd Build-Debug
  - conan install ..
  - cd ../Build-Release
  - conan install ..
script:
  - cd ../Build-Debug
  - cmake ..
  - make -j2
  - ctest -j2
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [[ "${COVERAGE}" == "1" ]]; then
         make gcov
         make lcov
         bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
    fi
  - cd ../Build-Release
  - cmake ..
  - make -j2
  - ctest -j2

